### ISSUE TITLE
What about other CPP files

### ISSUE THREAD

**Issue by 2063669460** [imhunterand/CS2-DMA-PROJECT#3]
Why is there no other CPP file, I can't update the new offset

**Comment by imhunterand** [comment]
what you mean, its the `project-dma` and the cpp file available on [DMA](https://github.com/imhunterand/CS2-DMA-PROJECT/tree/main/DMA)

**Comment by 2063669460** [comment]
yes
![image](https://github.com/imhunterand/CS2-DMA-PROJECT/assets/115350608/8f4b1779-5c8e-467c-9aae-f1db70693e72)

**Comment by imhunterand** [comment]
Hi there is `dma-project` a other cpp can be publicy.
